---
title: "ass2"
output: html_document
date: "2023-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)

#install.packages(c("coda","mvtnorm","devtools","loo", "here", "foreign","dagitty", "posterior","bayesplot"))
#devtools::install_github("rmcelreath/rethinking")

#install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
#install_cmdstan(cores = 2) # make sure you have C++ headers etc installed - e.g. COmmand Line Tools on MacoS
# see https://mc-stan.org/cmdstanr/articles/cmdstanr.html for mor

library(rethinking) # the sw for model specification (it then uses cmdstan)
library(foreign) # need to load funky data format
library(here) # make sure working dir is the same all the time
library(posterior)
library(bayesplot)
set.seed(100)
```

```{r}
#f_csv <- read.csv("nasa93_subset.csv")

f_arff <- read.arff("nasa93.arff")
 
# remove columns we don't need
#f_csv  <- f_csv [-c(1:5,7:11)]
#f_csv  <- f_csv [-c(1:16, 17:23)]

# convert Language (factor) to numeric
#for

str(f_csv )


```

```{r}
f_arff $pcap <- as.numeric(f_arff $pcap)
```

```{r}
f_arff  <- f_arff [-c(1:16, 18:23)]
```

```{r}
# sample randomly from a log-normal()
max(rlnorm(1e5, 0, 3))
```

```{r}
# sample randomly from a log-normal()
max(rlnorm(1e5, 0, 10))
```

```{r m0, message=FALSE, warning=FALSE, results='hide'}
m0 <- ulam(
  alist(
    act_effort ~ poisson(lambda),
    log(lambda) <- alpha, # log link
    alpha ~ normal(0, 3)
  ), data = f_arff, cores = 4, chains = 4, cmdstan = TRUE, log_lik = TRUE, iter = 5e3
)
```

```{r}
precis(m0,depth=2)
```

```{r}
exp(6.44)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide', fig.align='center'}
trankplot(m0)
```

```{r m1, message=FALSE, warning=FALSE, results='hide'}
m1 <- ulam(
    alist(
        act_effort ~ poisson(lambda),
        log(lambda) <- a_pcap[pcap], # each lang its own intercept
        a_pcap[pcap] ~ normal(0, 3)
    ), data = f_arff, cores = 4, chains = 4, cmdstan = TRUE, log_lik = TRUE
)
```

```{r}
precis(m1,depth=2)
```

```{r}
exp(5.85)

```

```{r}
exp(6.82)
```

```{r}
exp(6.52)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, results='hide', fig.align='center'}
trankplot(m1)
```

```{r, message=FALSE, warning=FALSE, results='hide'}
postcheck(m1, window = 81)
```

```{r}
compare(m0,m1, func=LOO)
```

```{r}
#confidence interval
10677.8 + c(-1,1) * 1.96 * 8784.84	
```

```{r}
plot(precis(m1, depth = 2, pars = "a_pcap"))
```

```{r}
post <- extract.samples(m1)

```

```{r}
str(post)
```

```{r}
#difference 
dens(post$a_pcap[,2] - post$a_pcap[,1])
```

```{r}
table(sign(post$a_pcap[,3] - post$a_pcap[,1]))
```

```{r, m2, message=FALSE, warning=FALSE, results='hide'}
m2 <- ulam(
    alist(
        act_effort ~ dgampois(lambda, phi), # phi to model variance
        log(lambda) <- a_pcap[pcap],
        a_pcap[pcap] ~ normal(0, 3),
        phi ~ exponential(1) # prior on the variance component phi
    ), data = f_arff, cores = 4, chains = 4, cmdstan = TRUE, log_lik = TRUE,
    control = list(adapt_delta=0.95)
)

```

```{r}
precis(m2,depth=2)
```

```{r}
postcheck(m2, window=81)
```

```{r loo, warning=FALSE, message=FALSE, fig.align='center'}
(loo_est <- compare(m0, m1, m2, func=LOO))
```

```{r}
loo_est[2,3] + c(-1,1) * loo_est[2,4] * 1.96

```

```{r}
plot(precis(m2, depth = 2, pars = "a_pcap", prob = 0.95))
```
